package com.mdrahman.stockbull.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

@Entity
@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
public class StockOrder {

    // Primary key for the entity, auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Date of the stock order (formatted as "yyyy-MM-dd")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date orderDate;

    private double stockPrice;
    private String stockSymbol;
    private double investAmount;

    // Type of card used for payment (e.g., credit card, debit card)
    private String cardType;

    // Card number used for payment (masked for security reasons)
    private String cardNumber;

    // Email of the user placing the stock order
    private String userEmail;

    private String address;

    // Additional comments or notes related to the stock order
    private String comment;

    // NoArgsConstructor, AllArgsConstructor, Getters
    // and setters for all properties of the Stock entity
    // (Generated by Lombok annotations)

    // toString method to display stock order information

    @Override
    public String toString() {
        return "StockOrder{" +
                "id=" + id +
                ", orderDate=" + orderDate +
                ", stockPrice=" + stockPrice +
                ", stockSymbol='" + stockSymbol + '\'' +
                ", investAmount=" + investAmount +
                ", cardType='" + cardType + '\'' +
                ", cardNumber='" + cardNumber + '\'' +
                ", userEmail='" + userEmail + '\'' +
                ", address='" + address + '\'' +
                ", comment='" + comment + '\'' +
                '}';
    }
}
