package com.mdrahman.stockbull.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
public class Stock {

    // Primary key for the entity, auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String stockName;
    private String stockSymbol;
    private double stockPrice;


    // NoArgsConstructor, AllArgsConstructor, Getters
    // and setters for all properties of the Stock entity
    // (Generated by Lombok annotations)

    // toString method to display stock information

    @Override
    public String toString() {
        return "Stock{" +
                "id=" + id +
                ", stockName='" + stockName + '\'' +
                ", stockSymbol='" + stockSymbol + '\'' +
                ", stockPrice=" + stockPrice +
                '}';
    }
}

